$(document).ready(function(){
    $("#SreiSnam").click(function(){
        $("#mSreiSnam").modal();
    });
    $("#Varin").click(function(){
        $("#mVarin").modal();
    });
    $("#SiemReap").click(function(){
        $("#mSiemRap").modal();
    });
    $("#KompongLeaeng").click(function(){
        $("#mKompongLeaeng").modal();
    });
    $("#Kralanh").click(function(){
        $("#mKralanh").modal();
    });
    $("#TaingKork").click(function(){
        $("#mTaingKork").modal();
    });
});
